[project]
name = "ai-queries"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "matplotlib>=3.10.3",
    "openai>=1.93.2",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
